### PR TITLE
Allow OCN_DATA nbt tag

### PR DESCRIPTION
**Pull request by YukonAppleGeek**
Prevents our custom nbt data from being filtered.

### CODE REVIEW

**Comment by mrapple** [comment]
Their either needs to be an API or the `OCN` prefix should be dropped/replaced.

**Comment by jedediah** [comment]
New patches should be on 1.8 https://github.com/OvercastNetwork/SportBukkit/tree/real1.8

**Comment by YukonAppleGeek** [comment]
Should the API be just an exception list to prevent NBT data from being lost or an entire ItemMetadata api?.

**Comment by YukonAppleGeek** [comment]
Moving this PR to 1.8 and keeping all NBT.

**Comment by YukonAppleGeek** [comment]
Post note: Spigot 1.8 has fixed this issue.

**Pull request closed without merging**
