### PR TITLE
[WIP] Rebase to CraftBukkit 1.9

### PR DESCRIPTION
**Pull request by jedediah**
Changes:
* pom.xml changes moved before all other patches
* Get rid of `v#_#R#` name mangling, because it confuses dev tools
* Replace `getEntityCount` and `setEntityCount` with just `allocateEntityId`
* Velocity in `BlockDispenseEvent` is now always used as velocity, never as a position. `BlockDispenseEntityEvent` has a new location property for this purpose.
* Make the pressure plate event spam patch actually do something
* Name mangling of Location.set* methods in the "Location extends Vector" patch moved to `mangle.csrg`. It used to be part of `deprecation-mappings.csrg`, but that was removed upstream.

Removed:
* "remove the remove queue" patch
* Entity visibility API, because it would now be much more difficult to implement
* Dropper inventory patch, appears to be fixed upstream
* `DataWatcher` optimization, because the original class changed too much
* Egg-spawner interaction patch, appears to be fixed upstream
* Our attribute API, except for item attribute modifiers, which is not implemented upstream yet
* "Fix damage cooldown reducing explosion knockback" because applied upstream
* "Fix HideFlags missing from NBT whitelist" because fixed upstream
* "Don't filter negative damage values" because applied upstream

Added:
* Arrow pickup rule API
* Arrow damage API
* Villager multi-trade API
* Absorption API
* Enhanced boss bar API
* Empty chunk API
* Team collision API
* Registration API - wrapper around Mojang's registration system for everything
* Update potion API to use registration
* Legacy potion support

Needs testing:

- [x] Interaction-override API
- [x] Is remove queue fixed?
- [x] Dropper inventory fixed?
- [x] Egg-spawner interaction cancelling
- [x] Custom replacement item in `PlayerItemConsumeEvent`

### CODE REVIEW

**Comment by jedediah** [comment]
Done all Bukkit patches and 86/127 CraftBukkit patches

**Comment by jedediah** [comment]
All patches done, builds fine. Just needs testing.

**Comment by twizmwazin** [comment]
The minecraft-api artifact for 1.9 is not in the repo yet, causing a build fail if it isn't installed locally.

**Comment by ryanwse** [comment]
Arrows also appear to be bugged, if you go in-game and shoot an arrow it appears to be invisible as it is flying through the air (and returns to its visible state when it lands). I can't confirm whether or not this is an upstream problem or SportBukkit specific.

**Comment by Pablete1234** [comment]
@jedediah 
What happened to `player.setAffectsSpawning(Boolean);` and `player.setCollidesWithEntities(Boolean)` ?

**Comment by jedediah** [comment]
Replaced with `Player.setInteractionOverride`

**Comment by Pablete1234** [comment]
@jedediah thanks

**Comment by Pablete1234** [comment]
@jedediah testing 1.9, cancelling the damage event (obervers trying to damage ingame players) also plays the hit sound for the ingame player.

**Comment by Pablete1234** [comment]
Playsound throws out of bounds exception if you don't include a player (/playsound sound slider)

**Comment by twizmwazin** [comment]
In the bossbar api patch, you're changing the parameter and return types to use BaseComponents rather than strings. While I agree with this improvement, it breaks compatibility with plugins written for bukkit. You should have String-based methods (deprecated?) to ensure compatibility. We shouldn't needlessly break compatibility.

**Comment by jedediah** [comment]
I think it's silly to be creating new APIs that support legacy text formatting, especially when the underlying  system doesn't even support it. We reimplemented a fair bit of the boss bar code anyway, and we don't want the extra work of maintaining the legacy methods.

**Comment by twizmwazin** [comment]
Re-implementing the legacy methods wouldn't be difficult though. There are already methods to quickly convert between strings and base components. I'd even suggest deprecating the legacy methods in SportBukkit to developers to avoid them and use the component formatting instead. The main issue here is that Sportbukkit breaking API compatibility with Bukkit means that users are not necessarily going to be able to run plugins written for Bukkit on there SportBukkit server.

**Comment by jedediah** [comment]
The bigger issue is that I don't want to invent new ways to use deprecated functionality. I'm going to see about changing the API upstream.

**Comment by twizmwazin** [comment]
I'm not sure that md_5 would support using components in bukkit, I'd see him more likely to have a spigot patch to add support for them there. However, for compatibility sake here, unless I'm missing something, is there any reason we can't just use `TextComponet.fromLegacyText(String message)` and `BaseComponent.toLegacyText(BaseComponent... components)`?

**Comment by jedediah** [comment]
Yes, that would do it. If it isn't changed upstream, then I'll put the legacy methods back.

**Comment by Pablete1234** [comment]
@jedediah Dropped items in the ground always look like stone to the client (when picked up they are the correct type and data)

**Comment by Pablete1234** [comment]
@jedediah player.setCollidesWithEntities doesn't prevent stoping boats (if an observers stands onfront of a boat, the player riding the boat can't move it)

**Pull request merged**
