### PR TITLE
Don't modify locale in getCurrentLocale()

### LINKED ISSUE #187: java.lang.IllegalArgumentException: Invalid locale format
Player#getCurrentLocale is throwing this error:

```
java.lang.IllegalArgumentException: Invalid locale format: en-GB
	at org.apache.commons.lang.LocaleUtils.toLocale(LocaleUtils.java:110) ~[sportbukkit-1.9.2-R0.1-SNAPSHOT.jar:git-Bukkit-8bf4588]
	at org.bukkit.craftbukkit.entity.CraftPlayer.getCurrentLocale(CraftPlayer.java:1812) ~[sportbukkit-1.9.2-R0.1-SNAPSHOT.jar:git-Bukkit-8bf4588]
```

The error occurs when using `English (US)` or `English (UK)` locale and I assume all others as well.

### PR DESCRIPTION
**Pull request by kblanks**
This fixes #187.

### CODE REVIEW

**Comment by TheMolkaPL** [comment]
You could use the `Apache Commons Lang3` library instead.

**Comment by kblanks** [comment]
All I did was remove the call to `replaceAll`, the rest of the code was part of SportBukkit already and didn't cause an issue.

**Comment by skipperguy12** [comment]
Thanks, worked for me

**Comment by IT3D** [comment]
👍  Could do with a merge.

**Comment by jedediah** [comment]
danke

**Pull request merged**
